#!/bin/bash

set -e

mkdir -p $ROCM_BUILD_DIR/rocm-core
cd $ROCM_BUILD_DIR/rocm-core

START_TIME=`date +%s`

cmake \
  -DCPACK_DEBIAN_PACKAGE_RELEASE="$CPACK_DEBIAN_PACKAGE_RELEASE" \
  -DCMAKE_INSTALL_PREFIX="$ROCM_INSTALL_DIR" \
  -DPROJECT_VERSION_MAJOR="$ROCM_MAJOR_VERSION" \
  -DPROJECT_VERSION_MINOR="$ROCM_MINOR_VERSION" \
  -DPROJECT_VERSION_PATCH="$ROCM_PATCH_VERSION" \
  -DROCM_VERSION="$ROCM_VERSION" \
  -DCPACK_GENERATOR=DEB \
  $ROCM_GIT_DIR/rocm-core

cmake --build .
cmake --build . --target package
$RUN_DPKG -i *.deb

END_TIME=`date +%s`
EXECUTING_TIME=`expr $END_TIME - $START_TIME`
echo "elapse : "$EXECUTING_TIME"s"
